In [1]:
import numpy as np
random_arr = np.random.rand(3, 3)
print("Random Array:\n", random_arr)

Random Array:
 [[0.9325733  0.5666691  0.57535395]
 [0.98402706 0.81884436 0.85235259]
 [0.22117762 0.23651791 0.88193676]]
